# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rts/tmp/main_window/devinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DevInfo(object):
    def setupUi(self, DevInfo):
        DevInfo.setObjectName("DevInfo")
        DevInfo.resize(510, 456)
        self.centralwidget = QtWidgets.QWidget(DevInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.getDevInfo = QtWidgets.QPushButton(self.centralwidget)
        self.getDevInfo.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.getDevInfo)
        DevInfo.setCentralWidget(self.centralwidget)

        self.retranslateUi(DevInfo)
        QtCore.QMetaObject.connectSlotsByName(DevInfo)

    def retranslateUi(self, DevInfo):
        _translate = QtCore.QCoreApplication.translate
        DevInfo.setWindowTitle(_translate("DevInfo", "MainWindow"))
        self.getDevInfo.setText(_translate("DevInfo", "Get device information"))
