# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rts/tmp/main_window/join_key.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JoinKey(object):
    def setupUi(self, JoinKey):
        JoinKey.setObjectName("JoinKey")
        JoinKey.resize(827, 600)
        self.centralwidget = QtWidgets.QWidget(JoinKey)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setEnabled(True)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 200, -1, 200)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.setKey = QtWidgets.QCheckBox(self.centralwidget)
        self.setKey.setObjectName("setKey")
        self.verticalLayout.addWidget(self.setKey)
        self.joinKey = QtWidgets.QLineEdit(self.centralwidget)
        self.joinKey.setObjectName("joinKey")
        self.verticalLayout.addWidget(self.joinKey)
        self.getJoinKey = QtWidgets.QPushButton(self.centralwidget)
        self.getJoinKey.setObjectName("getJoinKey")
        self.verticalLayout.addWidget(self.getJoinKey)
        self.horizontalLayout.addLayout(self.verticalLayout)
        JoinKey.setCentralWidget(self.centralwidget)

        self.retranslateUi(JoinKey)
        QtCore.QMetaObject.connectSlotsByName(JoinKey)

    def retranslateUi(self, JoinKey):
        _translate = QtCore.QCoreApplication.translate
        JoinKey.setWindowTitle(_translate("JoinKey", "Join key"))
        self.setKey.setText(_translate("JoinKey", "set_key"))
        self.joinKey.setPlaceholderText(_translate("JoinKey", "join_key"))
        self.getJoinKey.setText(_translate("JoinKey", "Get join key"))
