# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rts/tmp/main_window/mcu_telemetry.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_McuTelemetry(object):
    def setupUi(self, McuTelemetry):
        McuTelemetry.setObjectName("McuTelemetry")
        McuTelemetry.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(McuTelemetry)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.getMcuTelemetry = QtWidgets.QPushButton(self.centralwidget)
        self.getMcuTelemetry.setObjectName("getMcuTelemetry")
        self.verticalLayout.addWidget(self.getMcuTelemetry)
        McuTelemetry.setCentralWidget(self.centralwidget)

        self.retranslateUi(McuTelemetry)
        QtCore.QMetaObject.connectSlotsByName(McuTelemetry)

    def retranslateUi(self, McuTelemetry):
        _translate = QtCore.QCoreApplication.translate
        McuTelemetry.setWindowTitle(_translate("McuTelemetry", "MCU Telemetry"))
        self.getMcuTelemetry.setText(_translate("McuTelemetry", "Get MCU telemetry"))
