# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rts_icp_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rts_icp_common.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14rts_icp_common.proto\"\r\n\x0b\x64\x65vinfo_req\"@\n\x0c\x64\x65vinfo_resp\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66\x61mily\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\r\"1\n\x0cjoin_key_req\x12\x0f\n\x07set_key\x18\x01 \x01(\x08\x12\x10\n\x08join_key\x18\x02 \x01(\x0c\"!\n\rjoin_key_resp\x12\x10\n\x08join_key\x18\x02 \x01(\x0c\"\x13\n\x11mcu_telemetry_req\"v\n\x12mcu_telemetry_resp\x12\x17\n\x0f\x62\x61ttery_voltage\x18\x01 \x01(\x02\x12\x17\n\x0fmcu_temperature\x18\x02 \x01(\x02\x12\x15\n\rbattery_level\x18\x03 \x01(\r\x12\x17\n\x0f\x62\x61ttery_percent\x18\x04 \x01(\x02\x62\x06proto3')
)




_DEVINFO_REQ = _descriptor.Descriptor(
  name='devinfo_req',
  full_name='devinfo_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=37,
)


_DEVINFO_RESP = _descriptor.Descriptor(
  name='devinfo_resp',
  full_name='devinfo_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dev_eui', full_name='devinfo_resp.dev_eui', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='family', full_name='devinfo_resp.family', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='devinfo_resp.version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=103,
)


_JOIN_KEY_REQ = _descriptor.Descriptor(
  name='join_key_req',
  full_name='join_key_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='set_key', full_name='join_key_req.set_key', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='join_key', full_name='join_key_req.join_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=154,
)


_JOIN_KEY_RESP = _descriptor.Descriptor(
  name='join_key_resp',
  full_name='join_key_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='join_key', full_name='join_key_resp.join_key', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=189,
)


_MCU_TELEMETRY_REQ = _descriptor.Descriptor(
  name='mcu_telemetry_req',
  full_name='mcu_telemetry_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=210,
)


_MCU_TELEMETRY_RESP = _descriptor.Descriptor(
  name='mcu_telemetry_resp',
  full_name='mcu_telemetry_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='battery_voltage', full_name='mcu_telemetry_resp.battery_voltage', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mcu_temperature', full_name='mcu_telemetry_resp.mcu_temperature', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery_level', full_name='mcu_telemetry_resp.battery_level', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery_percent', full_name='mcu_telemetry_resp.battery_percent', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=330,
)

DESCRIPTOR.message_types_by_name['devinfo_req'] = _DEVINFO_REQ
DESCRIPTOR.message_types_by_name['devinfo_resp'] = _DEVINFO_RESP
DESCRIPTOR.message_types_by_name['join_key_req'] = _JOIN_KEY_REQ
DESCRIPTOR.message_types_by_name['join_key_resp'] = _JOIN_KEY_RESP
DESCRIPTOR.message_types_by_name['mcu_telemetry_req'] = _MCU_TELEMETRY_REQ
DESCRIPTOR.message_types_by_name['mcu_telemetry_resp'] = _MCU_TELEMETRY_RESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

devinfo_req = _reflection.GeneratedProtocolMessageType('devinfo_req', (_message.Message,), dict(
  DESCRIPTOR = _DEVINFO_REQ,
  __module__ = 'rts_icp_common_pb2'
  # @@protoc_insertion_point(class_scope:devinfo_req)
  ))
_sym_db.RegisterMessage(devinfo_req)

devinfo_resp = _reflection.GeneratedProtocolMessageType('devinfo_resp', (_message.Message,), dict(
  DESCRIPTOR = _DEVINFO_RESP,
  __module__ = 'rts_icp_common_pb2'
  # @@protoc_insertion_point(class_scope:devinfo_resp)
  ))
_sym_db.RegisterMessage(devinfo_resp)

join_key_req = _reflection.GeneratedProtocolMessageType('join_key_req', (_message.Message,), dict(
  DESCRIPTOR = _JOIN_KEY_REQ,
  __module__ = 'rts_icp_common_pb2'
  # @@protoc_insertion_point(class_scope:join_key_req)
  ))
_sym_db.RegisterMessage(join_key_req)

join_key_resp = _reflection.GeneratedProtocolMessageType('join_key_resp', (_message.Message,), dict(
  DESCRIPTOR = _JOIN_KEY_RESP,
  __module__ = 'rts_icp_common_pb2'
  # @@protoc_insertion_point(class_scope:join_key_resp)
  ))
_sym_db.RegisterMessage(join_key_resp)

mcu_telemetry_req = _reflection.GeneratedProtocolMessageType('mcu_telemetry_req', (_message.Message,), dict(
  DESCRIPTOR = _MCU_TELEMETRY_REQ,
  __module__ = 'rts_icp_common_pb2'
  # @@protoc_insertion_point(class_scope:mcu_telemetry_req)
  ))
_sym_db.RegisterMessage(mcu_telemetry_req)

mcu_telemetry_resp = _reflection.GeneratedProtocolMessageType('mcu_telemetry_resp', (_message.Message,), dict(
  DESCRIPTOR = _MCU_TELEMETRY_RESP,
  __module__ = 'rts_icp_common_pb2'
  # @@protoc_insertion_point(class_scope:mcu_telemetry_resp)
  ))
_sym_db.RegisterMessage(mcu_telemetry_resp)


# @@protoc_insertion_point(module_scope)
